name: MacGUI
on: workflow_dispatch
jobs:
  run:
    runs-on: macos-14
    steps:
    - name: Setup
      run: |
        brew install --cask ngrok
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all
        sudo dscl . -passwd /Users/runner "TauriTest123"
    - name: Tunnel
      run: |
        ngrok tcp 5900 --region in &
        sleep 5
        curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
        sleep 3600
